#!/bin/bash

DEBUG="\x1b[38;2;68;68;68m"
INFO="\x1b[1;34m"
WARNING="\x1b[1;33m"
ERROR="\x1b[1;31m"
CRITICAL="\x1b[37;41m"
NORMAL="\x1b[0m"

echo -ne '\x1b]0;HWDB Log\a'

tail -n 10 -f ~/.sisyphus/log.txt | sed \
    -e "s/\[DEBUG\]/${DEBUG}&${NORMAL}/" \
    -e "s/\[INFO\]/${INFO}&${NORMAL}/" \
    -e "s/\[WARNING\]/${WARNING}&${NORMAL}/" \
    -e "s/\[ERROR\]/${ERROR}&${NORMAL}/"
    -e "s/\[CRITICAL\]/${CRITICAL}&${NORMAL}/"
