#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Copyright (c) 2024 Regents of the University of Minnesota
Author: Alex Wagner <wagn0033@umn.edu>, Dept. of Physics and Astronomy

Logging Configuration

This file is automatically generated. You may edit it if you wish to
alter the logging format, but it may be overwritten when:

    (1) An exception is raised when attempting to exec() this file
    (2) The local namespace after calling exec() on this file does not
        contain "sisyphus_version", "overwrite_on_new_version", or 
        "contents"
    (3) Attempting to configure the logger with "contents" raises an
        exception
    (4) "sisyphus_version" does not match the version found in the 
        Sisyphus module, unless "overwrite_on_new_version" is set to
        False.
    (5) A future version alters logging in such a way that it is deemed
        no longer backwards-compatible with this copy.

Because this file may be overwritten, it is strongly recommended to
save your changes in another file after editing, just in case.
"""

sisyphus_version = "${SISYPHUS_VERSION}"
overwrite_on_new_version = True

import logging
class UTCFormatter(logging.Formatter):
    import time # There's something weird about namespaces in "exec" that
                # has forced me to do the import here. Go figure.
    converter = time.gmtime

contents = \
{
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "()": UTCFormatter,
            "format": "%(asctime)s.%(msecs)03d [%(levelname)s] %(filename)s, "
                        "line %(lineno)d (%(threadName)s): %(message)s",
            "datefmt": "%Y-%m-%dT%H:%M:%S"
        }
    },
    "handlers": {
        "logfile": {
            "level": "DEBUG",
            "formatter": "standard",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "/home/alexwagner/.sisyphus/log.txt",
            "maxBytes": 0x0100_0000,  # About 16MB
            "backupCount": 5
        }
    },
    "loggers": {
        "": {
            "handlers": ["logfile"],
            "level": "DEBUG",
            "propagate": False
        },
        "__main__": {
            "level": "DEBUG",
            "propagate": False
        },
        "chardet.universaldetector": {
            "handlers": ["logfile"],
            "level": "INFO",
            "propagate": False
        },
        "chardet.charsetprober": {
            "handlers": ["logfile"],
            "level": "INFO",
            "propagate": False
        },
        "numexpr.utils": {
            "handlers": ["logfile"],
            "level": "WARNING",
            "propagate": False
        },
        "urllib3.connectionpool": {
            "handlers": ["logfile"],
            "level": "INFO",
            "propagate": False
        }
    }
}
